#include <stdio.h>

int main(){
    printf("This is me first day learn C programming language.\n" );
    printf("I am excited to learn more about C programming!\n");
    printf("C programming is powerful and versatile.\n");
    printf("Let's write more code and have fun!\n");
    printf("I will upload this code in github,CSDN and blog \n");
    printf("I wish programerOG can hlep finding my mistake and take some suggestion, I will appreciate your advice . \n");
    printf("I will keep learning and improving my skills.\n");    
    printf("Thank you for your support and encouragement!\n");
    return 0;
/* End of the program . ps Why VScode can automatically write code comments? I don't know, but I like it.
   Even this comment is automatically generated by VScode.
   Please clear up my confusion, if you know the answer.
 */}

